input-output-hk/cardano-shell

.buildkite/pipeline.yml, README.md, nix/fetch-nixpkgs.nix, nix/nixpkgs-src.json, scripts/buildkite/cache-s3.nix, scripts/buildkite/default.nix, scripts/buildkite/rebuild.hs, stack.yaml
This uses the common `snapshot.yaml` from cardano-prelude, which we don't have yet for nix builds.
=> Buildkite pipeline with stack rebuild

README.md
This PR fixes the issue with the build badge checking all branches instead of only develop.
=> Fix badge to reflect only develop

stack-shell.nix, stack.yaml
https://github.com/input-output-hk/cardano-shell/issues/44
Bumping GHC.
=> [GH-44] Bump GHC version to 8.6.3.

app/NodeIPC/Main.hs, src/Cardano/Shell/NodeIPC.hs, src/Cardano/Shell/NodeIPC/Example.hs, src/Cardano/Shell/NodeIPC/Lib.hs, src/Cardano/Shell/NodeIPC/Message.hs, test/NodeIPCSpec.hs
=> Resolve technical debt

docs/Document.md
Create an document explaining what the shell does for non-developers.
=> [GH-24] Add understandable documentation for non-developers

app/NodeIPC/Main.hs, src/Cardano/Shell/NodeIPC.hs, src/Cardano/Shell/NodeIPC/Example.hs, src/Cardano/Shell/NodeIPC/Lib.hs, src/Cardano/Shell/NodeIPC/Message.hs, test/NodeIPCSpec.hs
https://github.com/input-output-hk/cardano-shell/issues/85
I can't say I really managed to create what I planned to do, but it's still not bad - the protocol handling function is extracted and I have fixed the IPC behavior when running for a longer time (more than a single message).
=> [GH-78] Generalize node IPC so it can be extended.

src/Cardano/Shell/Lib.hs
https://github.com/input-output-hk/cardano-shell/issues/144
This should be released to test with `validate-mainnet`.
Also, other exceptions should be noticed.
After confirming the exception is not swallowed, we can continue.
=> [GH-144] Rethrow cought exceptions to check if the application is throwing them.

cardano-shell.cabal, src/Cardano/Shell/NodeIPC.hs
Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
make it compatible with Win32
=> NodeIPC example removed from Win32 compilation

src/Cardano/Shell/Lib.hs
Continuing on from https://github.com/input-output-hk/cardano-shell/pull/145 and taking comments from other people into account.
=> [GH-144] Fix exception handling

app/Cardano/Shell/Features/Logging.hs, cabal.project, stack.yaml
Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
* the bracket functions do not require access to the configuration.
* export more bracket functions.
=> [GH-99] T5.1.1 simplified logging feature

src/Cardano/Shell/Constants/Types.hs, src/Cardano/Shell/Presets.hs
- When parsing `CardanoConfiguration` to see if we require a `NetworkMagic` value, we look for either `"RequiresMagic"` (for testnet) or `"RequiresNoMagic"` (for mainnet or staging).
- Change other types in `CardanoConfiguration` to match their corresponding types in `cardano-ledger`.
=> Fix various `CardanoConfiguration` types

default.nix, nix/iohk-nix-src.json, shell.nix, stack-shell.nix, stack.yaml
Only build dependencies, allow pure stack build.
(followup on https://github.com/input-output-hk/cardano-shell/pull/83#issuecomment-494381029)
=> Use new shellFor function to provide build env.

.buildkite/pipeline.yml, default.nix
https://github.com/input-output-hk/cardano-shell/issues/176
Adding the Coveralls test coverage (using Nix).
=> [GH-176] Add coveralls CI build coverage.

app/Cardano/Shell/Features/Logging.hs
https://github.com/input-output-hk/cardano-shell/pull/198
Fixing that the error gets raised if we _cannot_ find the file. Duh. :roll_eyes:
=> [GH-197] Fix the invalid check for file.

default.nix, release.nix, shell.nix, stack-shell.nix, stack.yaml
Also build shell on osx on hydra.
This fix https://buildkite.com/input-output-hk/cardano-shell/builds/688#61197167-e9f5-4953-9033-8815a06a9a2e
=> Add pkgconfig and systemd to nix-shell for stack.

app/Cardano/Shell/Features/Logging.hs
provides access to logging `Configuration`
Convenience! this is needed in cardano-node to flexibly work on logging, benchmarking and monitoring. Once this has been finished we might rethink on how to export the required functions through the logging layer in the shell.
=> Added Configuration in LoggingLayer.

app/Cardano/Shell/Features/Logging.hs
add integration of user-defined backends to logging
`LoggingLayer` now exports this function:
```
llAddBackend      :: Backend Text -> Text -> IO ()
```
=> allow integration with user-defined backends for logging

app/Cardano/Shell/Features/Networking.hs, app/Main.hs, default.nix, src/Cardano/Shell/Configuration/Lib.hs, src/Cardano/Shell/Constants/CLI.hs, src/Cardano/Shell/Constants/Types.hs, src/Cardano/Shell/Lib.hs, src/Cardano/Shell/Presets.hs
Take the next step in the partial-options-monoid implementation:
1. Finalisation functions that handle partiality
2. Cover `CardanoConfiguration`
3. Reverts to having unchanged `CardanoConfiguration` and `Core` types, using the `Last` type only in the `Partial`* variants.
Part of https://github.com/input-output-hk/cardano-shell/issues/210
=>  Next step in the partial-options-monoid implementation

app/daedalus-ipc.hs, cardano-shell.cabal, nix/.stack.nix/cardano-shell.nix, src/Cardano/Shell/DaedalusIPC.hs, src/Cardano/Shell/NodeIPC/General.hs
For #209.
I would also like to add the javascript test case from cardano-wallet, but am out of time today.
=> DaedalusIPC clean ups

src/Cardano/Shell/Presets.hs
Provide a value for the only non-defaulted preset field in `CardanoConfiguration`.
=> presets:  provide a default for pcoDBSerialiseVersion

src/Cardano/Shell/Configuration/Lib.hs, src/Cardano/Shell/Constants/CLI.hs, src/Cardano/Shell/Constants/PartialTypes.hs, src/Cardano/Shell/Presets.hs
https://github.com/input-output-hk/cardano-shell/issues/223
=> [GH-223] Add Block specific configuration options using CLI.

app/Cardano/Shell/Features/Networking.hs, app/Main.hs, src/Cardano/Shell/Configuration/Lib.hs, src/Cardano/Shell/Constants/CLI.hs, src/Cardano/Shell/Constants/PartialTypes.hs, src/Cardano/Shell/Constants/Types.hs, src/Cardano/Shell/Presets.hs
https://github.com/input-output-hk/cardano-shell/issues/235
Continuation from https://github.com/input-output-hk/cardano-shell/pull/232
=> [GH-235] Fixing nested configuration problems

app/Cardano/Shell/Features/Networking.hs, app/Main.hs, src/Cardano/Shell/Configuration/Lib.hs, src/Cardano/Shell/Constants/CLI.hs, src/Cardano/Shell/Constants/PartialTypes.hs, src/Cardano/Shell/Constants/Types.hs, src/Cardano/Shell/Presets.hs
https://github.com/input-output-hk/cardano-shell/issues/233
Also simplified the configuration handling that is now working on the top level.
=> [GH-233] Add NTP, Update, SSC, TXP, DLG specific configuration options using CLI

src/Cardano/Shell/Presets.hs
It was the hash of the genesis _block_, but should be and now is the
hash of the canonical mainnet-genesis.json.
=> fix mainnet genesis config hash

app/Cardano/Shell/Features/Networking.hs, app/Main.hs, cardano-shell.cabal, nix/.stack.nix/cardano-shell.nix, src/Cardano/Shell/Configuration/Lib.hs, src/Cardano/Shell/Constants/CLI.hs, src/Cardano/Shell/Constants/PartialTypes.hs, src/Cardano/Shell/Constants/Types.hs, src/Cardano/Shell/Presets.hs
https://github.com/input-output-hk/cardano-shell/issues/242
Can be run using `stack build --fast -j12 --nix && stack exec cardano-shell-exe --nix -- --log-config configuration/log-configuration.yaml --system-start 123456789 --slot-length 123456789` for example.
Also fixing https://github.com/input-output-hk/cardano-shell/pull/234/files/51c691aff16e719c94f3ad85b938094d6cba9185#diff-6111c9baeacdb1421faa3d1f338c9728
=> [GH-242] Add missing CLI options to shell.

release.nix, test.nix
Disables the perpetual `test-ipc`/Darwin test, that looked like so:
```
dns.js:246
this._handle = new ChannelWrap();
^
Error: EFILE
at new Resolver (dns.js:246:20)
at dns.js:377:23
at NativeModule.compile (bootstrap_node.js:600:7)
at NativeModule.require (bootstrap_node.js:545:18)
at net.js:45:13
at NativeModule.compile (bootstrap_node.js:600:7)
at NativeModule.require (bootstrap_node.js:545:18)
at createWritableStdioStream (internal/process/stdio.js:163:17)
at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
at console.js:249:38
builder for '/nix/store/8hl7r13yw4sbmyylcdpq2q3qj8d12jmk-test-ipc-x86_64-darwin.drv' failed with exit code 1
```
=> Disable the often-Darwin-impassable test-ipc on, well, Darwin

cardano-launcher/cardano-launcher.cabal, cardano-launcher/src/Cardano/Shell/Template.hs, cardano-launcher/test/Spec.hs, cardano-launcher/test/TemplateSpec.hs, nix/.stack.nix/cardano-launcher.nix
TODO: Resolve license issues. ~~Implement test cases~~.
This PR extract the code from `Data.Text.Temple` and modify so it can be used to perform env var substitution. 
https://github.com/input-output-hk/cardano-shell/issues/277
=> Extract code from Data.Text.Template

cardano-launcher/src/Cardano/Shell/Launcher.hs, release.nix
This PR would enable the hydra CI to run test suites for the `cardano-launcher`
https://hydra.iohk.io/build/1153187
Notice job `nix-tools.tests.cardano-launcher.cardano-launcher-test.x86_64-linux` has been added as one of the jobs.
Before: https://hydra.iohk.io/build/1153098#tabs-constituents
After: https://hydra.iohk.io/build/1153190#tabs-constituents
=> Add cardano-launcher-test to hydra ci

cardano-launcher/cardano-launcher.cabal, cardano-launcher/src/Cardano/Shell/Environment.hs, cardano-launcher/test/EnvironmentSpec.hs, cardano-launcher/test/Spec.hs, cardano-launcher/test/TemplateSpec.hs, nix/.stack.nix/cardano-launcher.nix
This PR introduces function `substituteEnvVars` which will traverse through yaml value and replace identifier text to actual value.
(e.g. if there was string value `${USER}`, it will look up environment variable name USER, then replace `${USER}` with that value)
https://github.com/input-output-hk/cardano-shell/issues/276
=> Supply context for the substitute environment variables

cardano-launcher/app/Mocks/Daedalus.hs
https://github.com/input-output-hk/cardano-shell/issues/310
Use `exitWith` from `System.Exit` so that mock exits itself with `ExitFailure 20` which is what we want.
=> Make it so that daedalus mock fails with ExitFailure 20

cardano-launcher/app/Main.hs, cardano-launcher/src/Cardano/Shell/Configuration.hs
solves https://github.com/input-output-hk/cardano-shell/issues/328
=> automatically disable tls if no path is configured

cardano-launcher/app/Main.hs, cardano-launcher/cardano-launcher.cabal, nix/.stack.nix/cardano-launcher.nix, nix/.stack.nix/default.nix, stack.yaml
https://github.com/input-output-hk/cardano-shell/issues/329
=> Disable terminal GUI on Windows

cardano-launcher/app/Main.hs, cardano-launcher/cardano-launcher.cabal, cardano-launcher/src/Cardano/Shell/Configuration.hs, cardano-launcher/src/Cardano/Shell/Launcher.hs, cardano-launcher/src/Cardano/Shell/Update/Lib.hs, cardano-launcher/test/UpdaterSpec.hs
https://github.com/input-output-hk/cardano-shell/issues/313
This enables us to test how the launcher behaves by returning specific exit codes.
=> [GH-313] Test together launcher/updater.

cardano-launcher/src/Cardano/Shell/Update/Lib.hs
https://github.com/input-output-hk/cardano-shell/issues/332
=> Disable console when update is running

cardano-launcher/README.md, cardano-launcher/app/Main.hs, cardano-launcher/cardano-launcher.cabal, cardano-launcher/src/Cardano/Shell/CLI.hs, cardano-launcher/src/Cardano/Shell/Launcher.hs, cardano-launcher/src/Cardano/Shell/Launcher/Types.hs, cardano-launcher/src/Cardano/Shell/Update/Lib.hs, cardano-launcher/test/LauncherSpec.hs, cardano-launcher/test/UpdaterSpec.hs, nix/.stack.nix/cardano-launcher.nix
https://github.com/input-output-hk/cardano-shell/issues/337
This enables testing from the CLI.
I also had to refactor the `CLI` module a bit, the CLI belongs at the top level.
If you want to provide stubbed exit codes, you can use something like:
```
stack exec cardano-launcher -- --config ./cardano-launcher/configuration/launcher/launcher-config.demo.yaml --wallet-exit-codes "[CLIExitCodeFailure 21, CLIExitCodeFailure 22, CLIExitCodeFailure 20, CLIExitCodeSuccess]" --updater-exit-codes "[CLIExitCodeFailure 1, CLIExitCodeSuccess]"
```
The exit codes are being popped from the list in order in which they were submitted. The result of this run is:
```
stack exec cardano-launcher -- --config ./cardano-launcher/configuration/launcher/launcher-config.demo.yaml --wallet-exit-codes …
```
=> [GH-337] Create CLI support for tests for both launcher and the updater.

cardano-shell/specs/CardanoShellSpec.lhs, cardano-shell/specs/tla/UpdateSystemWallet.tla
https://github.com/input-output-hk/cardano-shell/issues/355
Also fixing the state machine diagram in the (informal) spec.
`launcher_state_depth <- 10` for covering enough depth and finishing in some reasonable time.
=> [GH-355] Split TLA+ launcher spec into separate processes.

cardano-launcher/app/Main.hs, cardano-launcher/cardano-launcher.cabal, cardano-launcher/src/Cardano/Shell/Configuration.hs, cardano-launcher/src/Cardano/Shell/Launcher.hs, cardano-launcher/test/LauncherSpec.hs, nix/.stack.nix/cardano-launcher.nix
This PR changes tlsConfig to be an attribute in the launcher config instead of being a separate configuration file. We've tested it with daedalus flight and can confirm tls certificates are generated. This probably breaks tests.
=> tlsConfig passed via launcherConfig

.buildkite/pipeline.yml, cabal.project, default.nix, nix/default.nix, nix/pkgs.nix, nix/sources.json, shell.nix
Fixes the coverall tests broken in #362:
- Uses an older version of Stack, as newer versions have unresolved issues executing in a nix-shell.
- Adds an extra constraint to the cabal plan, as the upstream "iohk-monitoring" package is missing that constraint.
This is only a temporary fix. The stack build isn't reproducible, and in fact this PR wasn't working yesterday, so the stack runCoveralls tests rely on some unreliable environment, which is not ideal for CI. Our next step is to add coverage support to haskell.nix and use that to generate the coverage reports here (https://github.com/input-output-hk/haskell.nix/issues/443).
=> Fix coverall tests

.buildkite/pipeline.yml, README.rst, default.nix, nix/default.nix, nix/haskell.nix, nix/sources.json
- This is a small commit that makes two changes:
- Uses haskell.nix's new support for coverage to generate the
coverage report rather than using stack. As the CI already uses
haskell.nix to build the project and it's dependencies, this
should be faster than starting from scratch with stack. The
dependencies will be cached, so only the library needs to be
rebuilt with coverage support on.
- The coverage report generated by stack and generated by this
method are byte-for-byte the same.
- Implements a small conceptual shift in how we generate coverage
reports. Rather than generating the coverage report and uploading
it to coveralls.io from within Nix (this is not reproducible:
querying a web API could fail), we instead have Nix generate a
script that when run, will upload the coverage …
=> Use haskell.nix for coverage
