.hindent.yaml
.hlint.yaml
.stylish-haskell.yaml
ARCHITECTURE.md
README.md
app/Main.hs
cardano-prelude.nix
cardano-shell.cabal
cardano-shell.nix
src/Features/Logging.hs
src/Features/Networking.hs
src/Lib.hs
src/Types.hs
stack.yaml

https://github.com/input-output-hk/cardano-shell/issues/15
An improved version as suggested. Output when running(notice the timing in the first two features) :
```
Starting up logging!
Starting up networking!
Starting up networkingCardanoFeature!
Starting up loggingCardanoFeature!
Running node/wallet/whatever!
Running node/wallet/whatever!
Running node/wallet/whatever!
Running node/wallet/whatever!
Running node/wallet/whatever!
Exception occured!
Shutting down networkingCardanoFeature!
Shutting down networking feature!
Shutting down loggingCardanoFeature!
Shutting down logging feature!
```

[GH-15] Explore initial design of the `cardano-shell` architecture

---

.stylish-haskell.yaml
cardano-shell.cabal
cardano-shell.nix
src/Cardano/Shell/Features/Logging.hs
src/Cardano/Shell/Features/Networking.hs
src/Cardano/Shell/Lib.hs
src/Cardano/Shell/Types.hs
test/Spec.hs

https://github.com/input-output-hk/cardano-shell/issues/21

[GH-21] Write down tests for checking concurrency.

---

app/Cardano/Shell/Features/Logging.hs
app/Cardano/Shell/Features/Networking.hs
app/Main.hs
cardano-shell.cabal
src/Cardano/Shell/Configuration/Lib.hs
src/Cardano/Shell/Configuration/Types.hs
src/Cardano/Shell/Lib.hs
test/DhallConfigSpec.hs
test/Spec.hs

https://github.com/input-output-hk/cardano-shell/issues/27

[GH-27] Split project into library and executable

---

weekly-reports/2018-12-06.md
weekly-reports/2018-12-13.md
weekly-reports/2019-01-03.md

Adding missing and current weekly reports.

Add weekly reports, probably incomplete.

---

weekly-reports/2019-01-10.md
weekly-reports/2019-01-17.md

Add new weekly reports.

---

stack-hpc-coveralls.nix
weekly-reports/2019-01-24.md

Add weekly reports for week 4.

---

LAUNCHER.md
README.md

Adding documentation from meeting.

---

cardano-shell.cabal

 [#61] Expose `Cardano.Shell.Features.Logging`

---

test/NodeIPCSpec.hs

https://github.com/input-output-hk/cardano-shell/issues/73

Fix failing test cases

---

app/Cardano/Shell/Features/Logging.hs
cardano-shell.nix
config.nix
iohk-monitoring-basic-tracer.nix
iohk-monitoring.nix
libyaml.nix
stack.yaml

Updating the logging feature as seen in https://github.com/input-output-hk/cardano-shell/pull/72

WIP: Update logging feature.

---

.gitignore
app/Launcher/Main.hs
cardano-shell.cabal
cardano-shell.nix
cardano-sl-x509.nix
config.nix
configuration/cert-configuration.yaml
src/Cardano/Shell/Configuration/Types.hs
src/Cardano/Shell/Lib.hs
stack.yaml

https://github.com/input-output-hk/cardano-shell/issues/70

[GH-70] Implement certificate generation for the initial launcher

---

config.nix
iohk-monitoring-contra-tracer.nix
iohk-monitoring.nix
stack.yaml

Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
links to latest release 0.1.5.0 of iohk-monitoring-framework

updating logging to release 0.1.5.0

---

app/Cardano/Shell/Features/Logging.hs
cabal.project
cardano-shell.cabal
cardano-shell.nix
iohk-monitoring-contra-tracer.nix
iohk-monitoring.nix
src/Cardano/Shell/Types.hs
stack.yaml

added access to logging configuration in `LoggingFeature`
needed by https://github.com/input-output-hk/iohk-monitoring-framework/issues/228
issue #99
basis for `cardano-ledger` PR: https://github.com/input-output-hk/cardano-ledger/pull/487

[GH-99] T5.1.1 added configuration to logging feature

---

docs/Usage.md

Just a short summary of how they nicely built this app on top of the node-shell.

Usage description of cardano-shell in cardano-ledger's validate-mainnet app

---

README.md

Fixed README to reflect moving to `master` only.

[GH-179] Merge to master, fix README to reflect.

---

cardano-shell.cabal
src/Cardano/Shell/NodeIPC/Lib.hs
test/NodeIPCSMSpec.hs
test/NodeIPCSpec.hs

https://github.com/input-output-hk/cardano-shell/issues/160

[GH-160] Add shutdown message for node-IPC.

---

src/Cardano/Shell/Lib.hs
src/Cardano/Shell/NodeIPC/ServerExample.hs
src/Cardano/Shell/Presets.hs
test/Spec.hs

It would probably be worth making call compile errors into errors in CI.

Fix compiler warnings

---

PLAN.md

milestone planning

---

app/Cardano/Shell/Features/Logging.hs
app/Main.hs
src/Cardano/Shell/Lib.hs

https://github.com/input-output-hk/cardano-shell/issues/197

[GH-197] Improve the naming and comments for the CLI.

---

app/Main.hs
cardano-shell.cabal
src/Cardano/Shell/Configuration/Lib.hs
src/Cardano/Shell/Constants/CLI.hs
src/Cardano/Shell/Constants/PartialTypes.hs
src/Cardano/Shell/Constants/Types.hs
src/Cardano/Shell/Lib.hs
src/Cardano/Shell/Presets.hs

https://github.com/input-output-hk/cardano-shell/issues/218

[GH-218] Add Node specific configuration options using CLI.

---

cardano-shell.cabal
nix/.stack.nix/cardano-shell.nix
nix/.stack.nix/default.nix
src/Cardano/Shell/Constants/PartialTypes.hs
stack.yaml

https://github.com/input-output-hk/cardano-shell/issues/225

[GH-225] Derive monoids and semigroups.

---

src/Cardano/Shell/Configuration/Lib.hs
src/Cardano/Shell/Constants/CLI.hs
src/Cardano/Shell/Constants/PartialTypes.hs
src/Cardano/Shell/Constants/Types.hs
src/Cardano/Shell/Presets.hs

1. add `coPBftSigThd` to `Core`
2. make `coStaticKeySigningKeyFile` and `coStaticKeyDlgCertFile` optional

Core:  + coPBftSigThd; optionalise coStaticKeySigningKeyFile & coStaticKey

---

app/Launcher/Main.hs
cardano-shell.cabal
nix/.stack.nix/cardano-shell.nix
src/Cardano/Shell/Launcher.hs

https://github.com/input-output-hk/cardano-shell/issues/252
This PR extracts the `runWallet` function from launcher executable code `Main.hs` so that it can be tested.

Extract runWallet from Launcher main code

---

cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/src/Cardano/Shell/Update/Lib.hs

https://github.com/input-output-hk/cardano-shell/issues/266

[GH-266] Add an example how to separate the launcher code fore testing

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/test/LauncherSpec.hs
cardano-launcher/test/Spec.hs

https://github.com/input-output-hk/cardano-shell/issues/270

[GH-270] Add simple tests for exit codes handling and add safe mode.

---

Makefile
cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/src/Cardano/Shell/Update/Lib.hs
cardano-launcher/test/LauncherSMSpec.hs
cardano-launcher/test/LauncherSpec.hs
cardano-launcher/test/Spec.hs
cardano-launcher/test/UpdaterSpec.hs
nix/.stack.nix/cardano-launcher.nix

https://github.com/input-output-hk/cardano-shell/issues/273

[GH-273] Clean up and simplify the exit code functions.

---

cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/test/LauncherSMSpec.hs
cardano-launcher/test/LauncherSpec.hs
nix/iohk-nix-src.json

https://github.com/input-output-hk/cardano-shell/issues/282

[GH-282] Refactor and test wallet safe mode

---

cabal.project
cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
nix/.stack.nix/cardano-launcher.nix
nix/.stack.nix/contra-tracer.nix
nix/.stack.nix/default.nix
nix/.stack.nix/iohk-monitoring.nix
stack.yaml

Signed-off-by: Alexander Diemand <codieplusplus@apax.net>
logging in the launcher

added logging to launcher; newest revision of iohk-monitoring

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/CLI.hs
nix/.stack.nix/cardano-launcher.nix

https://github.com/input-output-hk/cardano-shell/issues/271
TODO: Merge https://github.com/input-output-hk/cardano-shell/pull/255 and rebase from master
How to run: `:main -c /path/to/config.yaml`

Implement CLI for the launcher

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/configuration/launcher/launcher-config.demo.yaml
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/test/LauncherSpec.hs
nix/.stack.nix/cardano-launcher.nix

https://github.com/input-output-hk/cardano-shell/issues/292

[GH-292] Set working directory based upon launcher-config.yaml

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/CLI.hs
cardano-launcher/src/Cardano/Shell/Environment.hs
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/test/LauncherSpec.hs
nix/.stack.nix/cardano-launcher.nix

https://github.com/input-output-hk/cardano-shell/issues/289
~~TODO: Merge this PR to master first~~ https://github.com/input-output-hk/cardano-shell/pull/275

Set environment variables that are needed

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/CLI.hs
cardano-launcher/src/Cardano/Shell/Configuration.hs
cardano-launcher/src/Cardano/Shell/Environment.hs
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/test/LauncherSpec.hs

https://github.com/input-output-hk/cardano-shell/issues/296

Move configuration related functions into its own module

---

cardano-launcher/configuration/launcher/launcher-config-demo.windows.yaml
updater-test-win.nix

https://github.com/input-output-hk/cardano-shell/issues/300

Update manual test script

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/src/Cardano/Shell/Types.hs
cardano-launcher/src/Cardano/Shell/Update/Lib.hs
cardano-launcher/test/UpdaterSpec.hs

https://github.com/input-output-hk/cardano-shell/issues/295
Refactored the code a bit so we can actually test it in more depth.

[GH-295] Add tests for the update system.

---

cardano-launcher/README.md

https://github.com/input-output-hk/cardano-shell/issues/298

Add readme for cardano-launcher

---

updater-test-win.nix

https://github.com/input-output-hk/cardano-shell/issues/304

Provide write permission to updater file

---

cardano-launcher/src/Cardano/Shell/Update/Lib.hs

Fixing the missing import I missed.
I'm not sure how this passed CI.

[GH-306] Added missing Data.Text import on Windows.

---

cardano-launcher/src/Cardano/Shell/CLI.hs

Fixing the env variable so the proper configuration can be used.

[GH-311] Fix the ENV variable so the launcher can run.

---

cardano-launcher/app/Main.hs
cardano-launcher/src/Cardano/Shell/CLI.hs
cardano-launcher/src/Cardano/Shell/Launcher.hs

https://github.com/input-output-hk/cardano-shell/issues/316

Add trace points in main as well as wallet run code

---

cardano-launcher/README.md
cardano-launcher/app/Main.hs
cardano-launcher/src/Cardano/Shell/CLI.hs
cardano-launcher/src/Cardano/Shell/Launcher.hs
cardano-launcher/src/Cardano/Shell/Update/Lib.hs
cardano-launcher/test/LauncherSpec.hs
cardano-launcher/test/UpdaterSpec.hs
release.nix

https://github.com/input-output-hk/cardano-shell/issues/319
It also includes a fix for https://github.com/input-output-hk/cardano-shell/issues/317 and a couple of other comments.

[GH-319] Fix behavior of running update on Windows.

---

cardano-launcher/configuration/launcher/launcher-config-demo.windows.yaml
cardano-launcher/configuration/launcher/launcher-config.demo.yaml
cardano-launcher/src/Cardano/Shell/Update/Lib.hs
cardano-launcher/test/LauncherSpec.hs

https://github.com/input-output-hk/cardano-shell/issues/323
This PR applies changes to the configuration files so that they're up-to-date

Update configuration file

---

cardano-launcher/src/Cardano/Shell/CLI.hs

https://github.com/input-output-hk/cardano-shell/issues/326

Remove DAEDALUS_CONFIG from being set

---

cardano-launcher/app/Main.hs
cardano-launcher/cardano-launcher.cabal
cardano-launcher/src/Cardano/Shell/Environment.hs
cardano-launcher/test/UpdaterSpec.hs
nix/.stack.nix/cardano-launcher.nix

https://github.com/input-output-hk/cardano-shell/issues/340

Use 'osascript' to display message on Mac

---

cardano-launcher/app/Main.hs
cardano-launcher/configuration/launcher/launcher-config.demo.yaml
cardano-launcher/src/Cardano/Shell/Configuration.hs

https://github.com/input-output-hk/cardano-shell/issues/339#issuecomment-550490262
This PR makes it so that lockfile is stored in `statePath`

Store lockfile at statePath

---

cardano-shell/specs/tla/Launcher.tla
cardano-shell/specs/tla/LauncherUpdateSystem.tla

https://github.com/input-output-hk/cardano-shell/issues/133
You can set the launcher depth check to 5, it's deep enough.

[GH-133] T9.4.2 complete launcher update system model.

---

CODEOWNERS

so they get invited for PR reviewing

include QA in CODEOWNERS

---

cabal.project
cardano-launcher/src/Cardano/Shell/Update/Types.hs
cardano-shell/cardano-shell.cabal
cardano-shell/src/Cardano/Shell/Lib.hs
cardano-shell/src/Cardano/Shell/NodeIPC/Lib.hs
cardano-shell/src/Cardano/Shell/NodeIPC/Message.hs
cardano-shell/test/NodeIPCSpec.hs
stack.yaml

The dependency update was needed in db-sync.
Biggest changes were due to updates to protolude (via cardano-prelude).

Update dependencies and Hackage index-state

---

doc/index.rst

* changed reference to locations

doc fix - changed reference to locations
